#!/bin/bash
REMOTE="locus@ded.increpare.com:sites/flickgame/beta"

rsync -avz --checksum \
  --include='*.*' \
  --exclude='.git' \
  --exclude='node_modules' \
  --exclude='agent-transcripts' \
  . "$REMOTE"

ssh locus@ded.increpare.com 'cd sites/flickgame/beta && perl gzipper'
